import Head from 'next/head';
import styled from 'styled-components';
import { Row, Col } from 'antd';
import { createClient } from 'contentful';

import FeaturedNewsSynopsis from '../../components/FeaturedNewsSynopsis';
import LatestNewsSynopsis from '../../components/LatestNewsSynopsis';
import StyledInput from '../../components/StyledInput';
import Layout from '../../components/Layout';

const Container = styled.div`
  height: 100vh;
  color: ${(props) => props.theme.colors.grey};
`;

const ContentWrapper = styled.div`
  margin: 45px 5%;
  .title {
    font-size: ${(props) => props.theme.fontSizes[6]};
    color: ${(props) => props.theme.colors.white};
    margin: 0 0 45px;
  }
  .sub-title {
    color: ${(props) => props.theme.colors.white};
    font-size: ${(props) => props.theme.fontSizes[2]};
    margin-bottom: 35px;
  }
`;

const LatestNews = styled.div`
  margin-bottom: 50px;
`;

const Main = styled.main``;

export async function getStaticProps() {
  const contentfulClient = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const response = await contentfulClient.getEntries({ content_type: 'news' });

  return {
    props: {
      news: response.items,
    },
    revalidate: 1,
  };
}

interface NewsProps {
  news: any;
}

export default function News({ news }: NewsProps) {
  return (
    <Container>
      <Head>
        <title>News - Ninja NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Main>
          <ContentWrapper>
            <div className="title">What's on NINJA</div>
            <StyledInput />
            <div className="title">Latest News</div>
            <LatestNews>
              <Row gutter={[12, 16]}>
                {news.map((newsItem: {}, index: number) => (
                  <Col key={index} xs={24} md={12} lg={8}>
                    <LatestNewsSynopsis newsItem={newsItem} />
                  </Col>
                ))}
              </Row>
            </LatestNews>
            <div className="title">Featured News</div>
            <FeaturedNewsSynopsis />
          </ContentWrapper>
        </Main>
      </Layout>
    </Container>
  );
}
