import Head from 'next/head';

export default function LeaderBoard() {
  return (
    <div>
      <Head>
        <title>About - Ninja NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to About Page</h1>
      </main>
    </div>
  );
}
