import Head from 'next/head';
import styled from 'styled-components';
import { Col, Row, Grid } from 'antd';
import Layout from '../components/Layout';
import HomeLeaderBoard from '../components/HomeLeaderBoard';
import HomeNFT from '../components/HomeNFT';
import Carousel from '../components/Carousel';
import Profile from './profile';

const { useBreakpoint } = Grid;

const Container = styled.div`
  min-height: 100vh;
  background: ${(props) => props.theme.colors.black};
`;

const Main = styled.main``;

const LeaderBoardAndNFT = styled.div`
  margin: 80px 5%;
`;

export default function Home() {
  const screen = useBreakpoint();

  return (
    <Profile />
    // <Container>
    //   <Head>
    //     <title></title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Layout>
    //   <Main>
    //     <Carousel />
    //     <LeaderBoardAndNFT>
    //       <Row gutter={[12, 16]}>
    //         <Col xs={24} lg={8}>
    //           <HomeLeaderBoard />
    //         </Col>
    //         <Col xs={24} lg={15} offset={screen.md ? 1 : 0}>
    //           <HomeNFT />
    //         </Col>
    //       </Row>
    //     </LeaderBoardAndNFT>
    //   </Main>
    //   </Layout>
    // </Container>
  );
}
