import { Row, Col } from 'antd';
import Head from 'next/head';
import styled from 'styled-components';
import Layout from '../components/Layout';
import PacksCard from '../components/PacksCard';

const Container = styled.div`
  height: 100vh;
`;

const ContentWrapper = styled.div`
  margin: 2% 5%;
`;
const Main = styled.main``;

export default function LeaderBoard() {
  return (
    <Container>
      <Head>
        <title>Packs - Ninja NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Main>
          <ContentWrapper>
            <Row gutter={[12, 16]}>
              <Col xs={24} lg={8}>
                <PacksCard />
              </Col>
              <Col xs={24} lg={15}></Col>
            </Row>
          </ContentWrapper>
        </Main>
      </Layout>
    </Container>
  );
}
